### ISSUE TITLE
Old APK

### ISSUE THREAD

**Issue by 89z** [onyxbits/raccoon4#104]
Is it possible to get old APK from this package, or just latest version? Similar to this:

https://www.apkmirror.com/uploads/?q=github-2

**Comment by onyxbits** [comment]
Yes "Market|Dowgrade App". However, this is the issue tracker. Not a support forum and also not the place to advertise your own tools (as you did in other issues).

**Comment by 89z** [comment]
> Yes "Market|Dowgrade App".

Is it possible to list the available versions?

> However, this is the issue tracker. Not a support forum

Is a support forum available?

> and also not the place to advertise your own tools (as you did in other issues).

Sorry about that. Someone had a problem, and I have a tool that works for their problem. Personally I dont see anything wrong with that, but out of respect I have removed the comment.

**Comment by onyxbits** [comment]
Support is a paid feature, but it does not cover software development questions.

**Comment by 89z** [comment]
I dont get why you cant just say yes or no, with regard to my question, but I guess thats your decision to make.

**Comment by onyxbits** [comment]
Just "yes" or "no" begs follow up questions, so I shortcutted to the follow up information.

**Comment by 89z** [comment]
Well, if it is possble to list available versions, but you dont want to answer because answering is a "paid feature", then I would gladly pay.

But it sounds like what youre saying, is that you cant even answer whether or not its something that possible now with raccoon, or possible in general. Given your responses so far, I am just going to assume its not something that you know how to do, and keep trying for my own solution. If I am wrong, and you do know some solution, then again I would be glad to pay for whatever that is.
