### ISSUE TITLE
Needbrowser 

### ISSUE THREAD

**Issue by VuzzyM** [onyxbits/raccoon4#109]
Needbrowser error, how to fix? 

![IMG_20220427_180758](https://user-images.githubusercontent.com/66425682/165550612-a856b62c-3ddd-4920-8a7f-8e1750365f17.jpg)

**Comment by VuzzyM** [comment]
> No, if it is configured without 2FS this is good, you can try to enable insecure authentication and set-up an app password.

How to set app password?

**Comment by jpstotz** [comment]
Please read the manual: https://support.google.com/accounts/answer/185833?hl=en
