### ISSUE TITLE
Refreshing token with gp-auth fails

### ISSUE THREAD

**Issue by hfreeb** [onyxbits/raccoon4#112]
When attempting to run `raccoon --gp-auth` to refresh the token I get a `BadAuthentication` response. I believe this is because the default HTTP client is used which fails Google's TLS fingerprinting.

The command works as expected when I modified the request to use a client configured to perform authentication, i.e. the client built in `LoginLogic#createLoginClient`.

**Comment by onyxbits** [comment]
Fixed in 4.22
