### ISSUE TITLE
Can't search by package id

### ISSUE THREAD

**Issue by babyquin** [onyxbits/raccoon4#114]
Looks like raccoon doesn't work well anymore. I can't search or download by name of package id.

Search results of: "pname:com.facebook.lite" return blank page.
Search results of: "com.facebook.lite" return related apps.

**Comment by onyxbits** [comment]
Paid support is available as part of the Raccoon Premium package. That's how the project is financed. Please do not try to work around this by abusing the **bug tracker** as a support forum.
