### ISSUE TITLE
No such thing as oauth_token

### ISSUE THREAD

**Issue by PQCraft** [onyxbits/raccoon4#119]
I get the `NeedsBrowser` error on all 3 of my accounts. I tried following [this](https://raccoon.onyxbits.de/blog/needs-browser-login-workaround/) but it wants me to find a cookie by the name of `oauth_token`. This cookie does not exist.

**Comment by ghost** [comment]
can you put a screenshot of the cookies you can see? not sure why that page doesn't give the actual URL, but this is it:

https://accounts.google.com/embedded/setup/android

**Comment by PQCraft** [comment]
This page hangs somehow. After I press "I agree", it sits there loading forever.
It does have the `oauth_token` cookie though so I guess this is solved lol
