### ISSUE TITLE
Raccoon 5.0.0

### ISSUE THREAD

**Issue by basilgello** [onyxbits/raccoon4#126]
Dear @onyxbits ,

For a long time I could not download apps with Raccoon so I ported changes from AuroraOSS gplayapi.

Eventually, this grew up into a patchset with the following improvements:

* Support AASToken refreshes and logins
* Add `--gp-create-profile` CLI switch
* Use Aurora account dispenser for profile creation
* Add known device profiles from gplayapi
* Replace Apache Commons httpcore with okhttp3
* Add SOCKS4/5 proxy support with authentication
* Refactor setup wizard so profiles can be created using either AASToken or Aurora dispenser with either known device profile or custom file exported by Aurora Store spoof manager.

I dont want to fragment the community with new forks, so how should I proceed to incorporate my patches and release 5.0 ?
We will need to tag 5.0 because users will have to re-initialize their Google credentials.

Should I PR my patchset openly here, or upload to a private fork and give you access first?

**Comment by basilgello** [comment]
TODO list:

* Make better error message when paid app is being downloaded and it was not purchased first
* Same for search rate limit
* Get permission from @whyorean about dispenser use in Raccoon
* Implement real device ADB profile generation
* Testing (a lot of)
* Try to get oauth token in desktop browser

**Comment by onyxbits** [comment]
Hi @basilgello ,
I'm sorry, but I cannot accept this pull request for a number of technical, organizational and legal reasons, including:

* The dispenser is a legal pitfall and the aurora people have never shown to be able to run one reliably. This is not something, I can take responsibility for.
* There already is a version 5 in development and I key my support contracts on the major version. Making short lived major versions is a no-go. Furthermore, GplayAPI is a chunk of technical debt, I want to get rid of, not extend support for.
* Your PR sounds like a large chunk of unknown code. I have running support contracts, it would be(come) subject to. This translates into an incalculable business risk for me.

**Comment by basilgello** [comment]
OK, thanks for information!

**Comment by jpstotz** [comment]
I find it sad that onyxbits directly rejected your request to provide enhancements to raccoon without even seeing it. Even if a PR contains a lot of "unknown code" to my experience often such code contains interesting ideas for enhancements or other ways to learn from it.

**Comment by 3052** [comment]
https://github.com/onyxbits/raccoon4/issues/127

**Comment by gamander** [comment]
[basilgello](https://github.com/basilgello) How can I access your patch for Raccoon? I can't get it to work either. I think you should just fork the project.

**Comment by gamander** [comment]
@basilgello How can I access your patch for Raccoon? I can't get it to work either. I think you should just fork the project.
