### ISSUE TITLE
Describe building in the Readme

### ISSUE THREAD

**Issue by DragoonAethis** [onyxbits/raccoon4#13]
The .jars built with `./gradlew -Pversion=4.0.1 assemble` do not start (`no main manifest attribute, in Raccoon-desktop-4.0.1.jar`), although the versions published on your website do. Specify that `-Pversion=something` is needed, and that the build itself should be done with launch4j tasks instead of the standard ones. (Those were fairly confusing 20 minutes :P)

**Comment by onyxbits** [comment]
Done
