### ISSUE TITLE
Compatibility: add a way to import an entire Raccoon v3 archive

### ISSUE THREAD

**Issue by onyxbits** [onyxbits/raccoon4#14]
There should be a File|Convert menuitem (someone please suggest a better name and a tooltip text). That only shows if an old Raccoon v3 installation is detected in Raccoon's homedir. 

Function: All apps (of all archives) found in the old installation should be piped through the GPlay Transfermanager (or a derivate of it) and automatically be linked to the current GPlay profile.

Discussion:

* Only Raccoon v3 users should see that option as it only applies to them. No need to confuse no users.
* Ignore the old config files, in particular the profile settings (account, GSF ID). Just dump everything we can find into the currrent Raccoon v4 profile. Trying to add a UI for fine control is not worth the effort. A user who wants to to sort things into different profiles can use a filemanager.
* Do NOT delete OR modify the contents of old archives! The user can do that with a filemanager AFTER ensuring that the old files are no longer needed.

**Comment by IzzySoft** [comment]
> File|Convert menuitem (someone please suggest a better name

„File|Migrate“ might be more appropriate. Cannot suggest a „better“ tooltip text as I don't know the current one :innocent: But maybe something like „Import your existing v3 archive“?

**Comment by onyxbits** [comment]
On second thought... doing it this way is utterly idiotic! Checking if there is something that could be imported just increases startup time (I'm obsessed with speed there) and requires a lot of code/work for something that is destined to fade into obscurity fast. I think, we are better off with an import script or something. In the long run, there needs to be a control in the App browser anyway through which the user can select how to update an an app (or to lock it from being updated at all).

**Comment by IzzySoft** [comment]
Technically, that has only to be checked on the first start. Then set an internal variable (which was initialized with `NULL`) to either `TRUE` (found something to import/migrate) or `FALSE` (nothing there). Once everything has been imported, it could be set to `FALSE` as well.

On the other hand the question is: is that worth the trouble? Why not simply have a menu item to check for an old installation, and decide then? Not enough space for that? :smile_cat:

**Comment by onyxbits** [comment]
Well, I just don't like that 10ms speed penalty on startup, everyone would have to pay in order to check if the item needs to be shown or not. Beyond that, doing this import thing is a giant PITA. Especially when OBB files get involved and everything needs to be hooked into the transfermanager (total overkill).

The stupid thing here being: the File|import dialog already supports multi file selection. The only thing thats missing is associating glueing together app id and profile id in a junction table. One could easily do that with a text editor in raccoondb_4.script:

INSERT INTO PLAYAPPOWNERSHIP VALUES(42,'my-profile')

**Comment by onyxbits** [comment]
Done
