### ISSUE TITLE
The java API (crawler) will work in future or not ?

### ISSUE THREAD

**Issue by IMAN4K** [onyxbits/raccoon4#21]
Hi and thanks for great client.
From the point that you're using [this](https://github.com/Akdeniz/google-play-crawler) java api and in [my issue](https://github.com/Akdeniz/google-play-crawler/issues/90) on that api page

>Android Cloud to Device Messaging (C2DM) is deprecated. The C2DM service will be shut down completely on 10/20/2015. Currently, C2DM accepts no new users, and grants no new quotas

Will this API working in future ?
Does google plan to remove [Client login](https://github.com/Akdeniz/google-play-crawler/blob/master/src/main/java/com/akdeniz/googleplaycrawler/GooglePlayAPI.java#L63) ?

Regards

**Comment by onyxbits** [comment]
Multipart answer:
1. I plan on eventually replacing akdeniz's API with my own implementation. It has numerous shortcomings already and the list is growing.
2. It's 2017 now and Raccoon is still operational ;).
3. I'm not really sure, if C2DM and Client Login are the same thing in this context. If Google were to deprecate CL, they'd lock out a shitton of legacy devices (which seems rather suicidal, considering Google's business model).
4. Last time, I had a look at Gapps, CL still seemed to be the method of choice for hooking up with Google services.
5. Of course, this is a very nice reminder for why it's worth getting the Raccoon premium: funding my research :).

**Comment by IMAN4K** [comment]
Well we assume Client login & `C2DM` will work!
However we're working on a cross-platform `LGPL` project and looking for a way to interact with market in a trustworthy manner if you wish you can count on us for your new API if it's open source (we hope!) we'll be happy if you share that with us or at least give us some point to start with.

And one more thing could we use `OAuth` with that java API for now ?

**Comment by onyxbits** [comment]
Yeah ... thanks, but I got enough on my own plate already to work on someone else's project, too.

**Comment by IMAN4K** [comment]
Ok thanks for the answers.
But what about `OAuth` could we use that without having API in developer console ?
Does `raccoon4` suppoert this ?
