### ISSUE TITLE
No more CLI?

### ISSUE THREAD

**Issue by alexdumitru89** [onyxbits/raccoon4#29]
I've been using Raccoon v3 from the CLI and I'm surprised to see there's no CLI in the new version. Are there any plans for it? 

BTW, I'm a huge fan!

Thanks

**Comment by onyxbits** [comment]
I wanted to drop CLI support entirely. It is too tempting to implement something obscure and rarely needed via commandline switches, just to realize that it is not that obscure and rarely needed after all and that people will start emailing you how to use the commandline.

That being said, yes, I get a lot of requests to bring back the commandline, too. Seems like a no-win situation for me and I'll bring the CLI back.

**Comment by alexdumitru89** [comment]
That sounds great. 

Thanks!
