### ISSUE TITLE
How did you came across for EncryptedPasswd in login params ?

### ISSUE THREAD

**Issue by IMAN4K** [onyxbits/raccoon4#37]
Hi @onyxbits 
I found about 3 changes in API login code base comparing to akdeniz's API :
1. [Replacing ](https://github.com/onyxbits/raccoon4/blob/master/src/main/java/com/akdeniz/googleplaycrawler/GooglePlayAPI.java#L299)`Passwd` with `EncryptedPasswd` (which require new encrypted value)
2. Changing `sdk_version` to `17` (seems to be year!)
3. Removing `client_sig` params
3. Adding new params `add_account`

I was wonder if you could help us on how did you figured these out ?
How could we change this private API (akdeniz's API) if necessary ?
Is there any source or related link you think it will help us to find the right http post format?

I know, you spend lost of time to find out what should be change for new login procedure BUT i'll appreciate it if you at least tell us how to find workaround for future issues.
Regards.

**Comment by onyxbits** [comment]
> I was wonder if you could help us on how did you figured these out ?

I would rather not tell. It's a long story, too much trouble writing it down and not entertaining enough to make it worth the while. Simply go with the results.

> How could we change this private API (akdeniz's API) if necessary ?

The same way, I did? Fork it?

> Is there any source or related link you think it will help us to find the right http post format?

No, not contents of my brain are not linkable.

> I know, you spend lost of time to find out what should be change for new login procedure BUT i'll appreciate it if you at least tell us how to find workaround for future issues.

Can't. You might as well ask me how to win the Nobel prize. There is no step by step guide for how to do these things, you simply have to figure them out.

**Comment by IMAN4K** [comment]
OK.
You didn't tell anything!
Maybe starting by sniffing request/replies on some legacy android device will put me on the right direction...

**Comment by onyxbits** [comment]
Won't

a) That would only tell you what is being sent/received (but not how the encryptionprocess works)...
b) ...if the traffic wasn't HTTPS (you'd have to MITM the traffic after injecting your own root certificate into the device).
c) "Legacy" is the keyword: you are not interested in how things were before, but in how they are now.

Why you'd want to go through this is beyond me, though. While I don't care to talk about how to figure these things out, I do publish the my results.

**Comment by IMAN4K** [comment]
Well.
I will use your updates (and thanks for it, really) in my open source project BUT if one day you decide not to commit anymore then i'm in a big trouble...
