### ISSUE TITLE
Error when click download app

### ISSUE THREAD

**Issue by sharifStrudent** [onyxbits/raccoon4#41]
Hi,
Today I can't download any app using Raccoon, it give me Error!
I think google make a change in API.

**Comment by shamolvshu** [comment]
Yes, I got the error also.

**Comment by onyxbits** [comment]
http://blog.onyxbits.de/raccoon-app-search-works-download-doesnt-658/

**Comment by onyxbits** [comment]
http://blog.onyxbits.de/raccoon-error-when-downloading-continued-662/

**Comment by shamolvshu** [comment]
Thanks the author contribution,
@sharifStrudent if you not pull the author least commit, you can change the the User-Agent: "Android-Finsky/4.4.3 (api=3,versionCode=8016014,sdk=23,device=hammerhead,hardware=hammerhead,product=hammerhead)".

**Comment by onyxbits** [comment]
Should be resolved with v4.1.4
