### ISSUE TITLE
Fix for Raccoon Can Search for, but not Download Certain Apps

### ISSUE THREAD

**Issue by bcas9472** [onyxbits/raccoon4#44]
I am not sure if this is the right fix, or if Patrick will decide to do something different, but the problem of not being able to download certain apps from Play Store using Raccoon dates back for me all the way to 4.0 when I started using it. I've been able to reproduce and fix the problem on my Raccoon with no other impact.

https://youtu.be/mN5naAPk-GE

java -cp raccoon.jar org.hsqldb.util.DatabaseManagerSwing --url jdbc:hsqldb:file:raccoondb_4

ALTER TABLE PUBLIC.PERMISSIONS ALTER COLUMN NAME VARCHAR(1000)
ALTER TABLE PUBLIC.ANDROIDAPPS ALTER COLUMN NAME VARCHAR(1000)

This 100% fixed my downloading/importing problem.  I batch imported over 200 apk's without issue or a hicup.

Example app of causing issue: Samsung Browser Beta (com.sec.android.app.sbrowser.beta)

Couldn't download or Import before the fix.

[DESCRIBE_TABLES_AFTER.txt](https://github.com/onyxbits/raccoon4/files/1348472/DESCRIBE_TABLES_AFTER.txt)

[DESCRIBE_TABLES_BEFORE.txt]
(https://github.com/onyxbits/raccoon4/files/1348473/DESCRIBE_TABLES_BEFORE.txt)

[DESCRIBE_TABLES_sqlext.txt](https://github.com/onyxbits/raccoon4/files/1348476/DESCRIBE_TABLES_sqlext.txt)

[raccoondb_4_BEFORE.scriptext.txt](https://github.com/onyxbits/raccoon4/files/1348482/raccoondb_4_BEFORE.scriptext.txt)

[raccoondb_4_AFTER.scriptext.txt](https://github.com/onyxbits/raccoon4/files/1348480/raccoondb_4_AFTER.scriptext.txt)

**Comment by bcas9472** [comment]
Sorry I dont know how to fork and fix and all that - not a developer.

**Comment by onyxbits** [comment]
It kinda is the right thing to do (https://github.com/onyxbits/raccoon4/issues/42). Some app makers appearently use permissions in a creative way. 
1000 is not a good number though. The 255 character limit was justified by assuming that no one would use longer permissions and then the string length could be stored in a single byte. Since we obviously need two bytes, we might as well bump the limit to 32k (gotta read up on that, though. Not sure how hsqldb handles it).

**Comment by bcas9472** [comment]
Thanks for taking the time to read it, I appreciate the app you work on I use it everyday.  Like I said, Im not a developer but it sure was fund involving myself in trying to fix it so I can use it more.
If you need me to test anything let me know.

**Comment by onyxbits** [comment]
Fixed
