### ISSUE TITLE
Change language of the Play Store

### ISSUE THREAD

**Issue by Sopor-** [onyxbits/raccoon4#55]
It would have been nice if it was possible to change the Play Store language and download location of the apps. Not everyone want to have it in Documents.
I did found the command line options but those seems to not work in GUI mode :(

**Comment by onyxbits** [comment]
the .exe wrapper doesn't hand commandline arguments through, you have to use the .jar version. The playstore language is chosen according to the system locale (you can also change that on the on the commandline with the -Dlocale property).
