### ISSUE TITLE
Offer users a free of cost way to report bugs

### ISSUE THREAD

**Issue by jidanni** [onyxbits/raccoon4#64]
User discovers a bug.

User wishes to report it.

User finds https://raccoon.onyxbits.de/support/

But that asks for money to report bugs.

Solution:
- https://raccoon.onyxbits.de/support/ and
- https://billing.onyxbits.de/

should also include a link to https://github.com/onyxbits/raccoon4/issues/ .

**Comment by onyxbits** [comment]
Fixed

**Comment by jidanni** [comment]
https://billing.onyxbits.de/ should also mention the bug tracker.

**Comment by onyxbits** [comment]
No, definitely not.
