### ISSUE TITLE
FAQ should say if one still must unlock features if one has the source.

### ISSUE THREAD

**Issue by jidanni** [onyxbits/raccoon4#65]
https://billing.onyxbits.de/ says one can pay to "unlock" features.

https://raccoon.onyxbits.de/apk-downloader-v4/about-raccoon/#about-raccoon says Raccoon is Open Source.

So maybe https://billing.onyxbits.de/faq should say if one still must unlock features if one has the source.

See also #11.

**Comment by onyxbits** [comment]
Not sure what to do here. I don't see the conflict.

**Comment by jidanni** [comment]
Maybe in the FAQ say:

Q: Do I have to pay to unlock the features?
A: Yes. Or you can hack the [source](https://github.com/onyxbits/raccoon4).

**Comment by onyxbits** [comment]
The point here is to fund the project.
