### ISSUE TITLE
Version 4.18.0 fails to compile maven modules

### ISSUE THREAD

**Issue by ford--prefect** [onyxbits/raccoon4#94]
When building the recently released 4.18.0 on Archlinux via the AUR package with
`gradle -Pversion=4.18.0 fatJar`

I get the following error:

`A problem occurred evaluating root project 'Raccoon-desktop'.
> Could not find method compile() for arguments [net.dongliu:apk-parser:2.6.10] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler`

Uncommenting the apk-parser yield the same result with the next maven module, so this seems to be a general issue. Is this my fault, did I miss a change? Or is this a real issue?

**Comment by jpstotz** [comment]
Instead of using your local gradle version you should better use `gradlew` which currently defaults to Gradle 6.8.2. Different gradle versions can cause errors like those you have encountered.

**Comment by ford--prefect** [comment]
Thanks, that indeed solved the problem.
