### ISSUE TITLE
Auth broken

### ISSUE THREAD

**Issue by morethanhater** [onyxbits/raccoon4#97]
Hello.
After this "Bad Authentication", which described at your blog, i got the same problem.
So, i decided to create new account, using new real smartphone and other ISP and check the whole thing out.
Sadly, i got same error.
I did enable access to account for less safe apps and approved auth request through security section on website. No luck.
DummyDroid says, that account is disabled.

First time i did create issue at old repo, sorry. Now it's more clearer.

**Comment by jpstotz** [comment]
There was already a discussion o that topic in #95 which was closed for an unknown reason.
